[functions.send-application-mail]
verify_jwt = false

[functions.send-contact-mail]
verify_jwt = false

[functions.send-meeting-invite-mail]
verify_jwt = false

[functions.get-top-news]
verify_jwt = false