[functions.send-application-mail]
verify_jwt = false

[functions.send-contact-mail]
verify_jwt = false

[functions.send-meeting-invite-mail]
verify_jwt = false

[functions.get-top-news]
verify_jwt = false

[functions.get-member-data]
verify_jwt = false

[functions.login-admin]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.member-password-reset]
verify_jwt = false

[functions.send-membership-invoice-mail]
verify_jwt = false